# -*- coding: utf-8 -*-
"""hello.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wf4VT8cV6x7LtBfekcTzNHNVy8Wtu7hG
"""

import streamlit as st
st.heade('puppy')
st.write('puppy')